version: "3"

services:
  server:
    build: ./COD_stats_server
    container_name: COD_stats_server
    restart: always
    ports:
        - "8080:8080"
    networks:
      - back
    volumes:
      - ./COD_stats_server/src:/app/src
      - ./COD_stats_server/swagger.yaml:/app/swagger.yaml
      - /app/node_modules
    env_file:
      - config.env
 
  client:
    build: ./COD_stats_client
    container_name: COD_stats_client
    restart: always
    ports:
        - "8081:8081"
    networks:
      - back
    volumes:
      - ./COD_stats_client/src:/app/src

    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - config.env

  api_database:
    image: mongo
    container_name: "api_database"
    volumes: 
      - ./api-db-volume:/data/db/
    ports: 
      - "127.0.0.1:27017:27017"
    networks:
      - back
    restart: always

  database_express:
    image: mongo-express
    ports:
      - "5000:8081"
    env_file:
      - config.env
    environment:
      ME_CONFIG_MONGODB_SERVER: api_database
      ME_CONFIG_MONGODB_URL: mongodb://api_database:27017
    networks:
      - back
    logging:
      driver: none
  
networks: 
  back:
    driver: bridge

